name: Release
on:
  release:
    types: [created]
env:
  APP_NAME: free-park-spa
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get Version from Tag
        run: |
          echo "VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF:11}"

      - uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Build
        run: |
          npm --no-git-tag-version version ${VERSION}
          npm ci
          npm run build
          cd dist/ && zip -r ${{ env.APP_NAME }}-${{ env.VERSION }}.zip .
        env:
          VUE_APP_API_BASE_URL: ${{ secrets.API_BASE_URL }}
          VUE_APP_VERSION: ${{ env.VERSION }}

      - name: Get Release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./dist/${{ env.APP_NAME }}-${{ env.VERSION }}.zip
          asset_name: ${{ env.APP_NAME }}-${{ env.VERSION }}.zip
          asset_content_type: application/octet-stream
